Repository googleapis/nodejs-os-login, pull requests merged in 2020-05, with the labels that each got.

#342 fix: regen protos and tests, formatting
  synth.metadata
  test/gapic_os_login_service_v1.ts
  test/gapic_os_login_service_v1beta.ts
Labels: automerge, cla: yes

#343 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#344 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
