Repository googleapis/nodejs-os-login, pull requests merged in 2020-07, with the labels that each got.

#355 build: use bazel build
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/os_login_service_client_config.json
  src/v1/os_login_service_proto_list.json
  src/v1beta/os_login_service_client_config.json
  src/v1beta/os_login_service_proto_list.json
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#356 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#358 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#360 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#363 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#364 build: missing closing paren in publish script, delete template for Node 8, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#365 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#366 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#367 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#371 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
