Repository googleapis/nodejs-os-login, pull requests merged in 2020-11, with the labels that each got.

#395 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#396 build: v1.OsLoginServiceClient
  src/index.ts
  synth.metadata
Labels: api: oslogin, cla: yes, context: none

#397 fix: do not modify options object, use defaultScopes
  package.json
  src/v1/os_login_service_client.ts
  src/v1beta/os_login_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: oslogin, automerge, cla: yes

#401 fix: check for fetch on window
  protos/protos.json
  src/v1/os_login_service_client.ts
  src/v1beta/os_login_service_client.ts
  synth.metadata
Labels: api: oslogin, cla: yes, context: partial

#403 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full
